import { useState, useEffect } from "react";
import { Logout } from "../components/dashboard/menu/buttons/logout";
import { Perfil } from "../components/dashboard/menu/perfil";
import { Balance } from "../components/dashboard/balance";
import { SendMoney } from "../components/dashboard/send-money";
import { History } from "../components/dashboard/history";
import { Transactions } from "../components/dashboard/transactions";
import Head from "next/head";

const me = { picture: "https://avatars.githubusercontent.com/u/5620529?v=4", id: "f", name: "Guilherme Amorim" };

export default function Dashboard() {

	const [balance, setBalance] = useState(0);

	useEffect(() => {
		setBalance(100)
	}, [balance]);

	return (
		<div>
			<Head>
				<title>NG - Trybe</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex flex-row">
				<div className="w-1/6 h-screen bg-purple-900 p-4 flex flex-col justify-between fixed">
					<Perfil me={me} />
					<Logout />
				</div>
				<div className="w-1/6"></div>
				<div className="w-5/6 flex flex-col gap-4 p-4">
					<Balance balance={balance} />
					<SendMoney />
					<History />
					<Transactions />
				</div>
			</div>
		</div>
	);
}
